### ISSUE TITLE
More than three states causes multiple errors when trying to export

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#100]
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/e4ced43d-90f1-4a28-b0e6-3b7d503db85a)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/ad7b24b0-4525-48f6-8020-17adf4cb3273)

**Comment by mca-sh** [comment]
Hello Sidney and thank you for the bug report.
It seems the error comes from some parameters of the noise model that are ill-defined and it should be handled by the software: I need to correct this.
Could you please report a screenshot of the "Video parameters" panel?
You apparently chose the "Nexp-N" noise model.

**Comment by snguyen49** [comment]
Hi Melodie,

I usually keep everything the same in the video parameters panel except for the amount of traces and noise model. I use the Nexp-N noise model and I change the number of traces 1000 instead of the defaulted 4000.
[cid:aa526a0e-7c90-450c-a286-e4358861ade7]

Many Thanks,
Sydney Nguyen
________________________________

**Comment by mca-sh** [comment]
I was finally able to reproduce and fix the bug.
Thank you very much for your contribution!
You can find the corrected version here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip
(or just git pull if you are using git)

Mélodie

**Comment by snguyen49** [comment]
Thank you so much!

Many Thanks,
Sydney Nguyen
________________________________
