### ISSUE TITLE
simulation pre-set file not read properly

### ISSUE THREAD

**Issue by LeonieUniFR** [RNA-FRETools/MASH-FRET#104]
Hello,
I encountered some problems when running simulations with MASH-FRET. I created presetFiles.mat with createSimPrm.m.
1. When I entered values for trans_prob and left trans_rates empty nothing was imported when using 'import presets'. Is it not sufficient to give only the probabilities?
2. When I entered values for trans_rates and left trans_prob empty rates were imported when using 'import presets' (numbers appeared in the Thermodynamic model and turned grey). BUT the resulting traces don’t fit my numbers). When I add the same rates by hand into the table on the GUI completely different traces (ones which fit my rates) are generated. 
I set the frame rate to 1 to prevent some frames^-1 to seconds^-1 miscalculations.
3. I created a transition matrix with 4 states where the molecule can only go in one direction. The state sequence should always be 13241324… But when I generate traces the state sequence in the exported ASCII does not match. Are some states not in the traces because their dwell time is too short and they are missed?#

Thank you for your help,
Leonie
Email: leonie.vollmar@pc.uni-freiburg.de

Rates in GUI -> traces with long dwell times
![ratesinGUI](https://github.com/RNA-FRETools/MASH-FRET/assets/144801834/94347476-6b27-4dc7-981a-160f48cc7702)
Rates imported via presets -> very short dwell times
![ratesinpresets](https://github.com/RNA-FRETools/MASH-FRET/assets/144801834/75376a46-7346-4cb8-a4fa-2809340bdb1d)

**Comment by LeonieUniFR** [comment]
Hello Mélodie,
Thank you for you quick reply. 
1. Okay, I will only use `trans_rates` from now on. Also thank you for pointing out that the units of `trans_rates` is per time interval and not per second. This led to some confusion on my side.
2. I tested your new version. Unfortunately it crashed and gave the following error in `buildModel` (see screenshot). I then stopped the program right bevor the error. When I understand it correctly the size of `ip` seems to be the problem. Shouldn't it be `ip =ip_all(n,:)'` in line 86 in `buildModel` instead of `ip = ip_all(:,n)'`?
![error_buildModel](https://github.com/RNA-FRETools/MASH-FRET/assets/144801834/4ae59131-60e2-4b50-b123-e61a91ba4a1a)
3. Thanks. It totally makes sense when looking at the exported dwell times.

Best,
Leonie

**Comment by mca-sh** [comment]
Ouch.. I made a mess here
Almost, actually it should be `ip_all(n,:)`, 
Thank you for your feedback, modifications have been made to the same branch, You can use the same download link I gave you previously.
Mélodie

**Comment by LeonieUniFR** [comment]
Hi Mélodie,
unfortunately the dimentions still produced an error in `buildModel` and a new error turned up:

> Matrix dimensions must agree.
> Error in buildModel (line 72)
>     ip_all = tau_all./repmat(sum(tau_all,1),[J,1,1])'; % [J-by-N]

I then had to make a change in
line 72 `ip_all = tau_all./repmat(sum(tau_all,1),[J,1,1]); % removed '` 
and add an additional 
line 73 `ip_all = ip_all'; % now transposed`

now `ip_all `has the same dimentions when being calculated or when coming from presets.
Now it works :)

Best,
Leonie

**Comment by mca-sh** [comment]
Oh my.. 
Thank you Leonie for the feedback AND the bug fix.
I will add this correction to the source code and close this issue then.
Do not hesitate to post a new issue anytime you encounter such malfunctioning, this is very helpful for us.
Best,
Mélodie
