### ISSUE TITLE
I am unable to click on save after importing video. These errors are occurring

### ISSUE THREAD

**Issue by gtripathi1** [RNA-FRETools/MASH-FRET#120]
Error in push_setExpSet_save (line 53)
h = guidata(h_fig0);
 
Error while evaluating UIControl Callback.

Error using guidata
Object must be a figure or one of its child objects.

Error in push_setExpSet_save (line 53)
h = guidata(h_fig0);
 
Error while evaluating UIControl Callback.

Error using guidata
Object must be a figure or one of its child objects.

Error in push_setExpSet_save (line 53)
h = guidata(h_fig0);
 
Error while evaluating UIControl Callback.

Email- gtripathi1@student.gsu.edu

**Comment by mca-sh** [comment]
Hello,
In absence of response, I close this issue now.
Do not hesitate to open a new one if you encounter another bug.
Best,
Mélodie
