### ISSUE TITLE
Calculate traces only works for .sira files not .avi files

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#121]
Hi Melodie,

Just coming on here to let you know that a consistent error has caught my attention pertaining to calculating traces. When using a .avi video file, the program generates an error even after following all proper procedures. I went back and reran it with a .sira file and found that it worked. It is not a major problem for me, but I figured that you would want to know if it was not your intention to make it this way. Here is the error code that comes up.
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/b42ddaae-de91-4cba-90f4-574b1443ccfe)

Sydney Nguyen

**Comment by mca-sh** [comment]
Hi Sydney and thanks again for the bug report.

Indeed, the .avi video files can not be used to create traces because the intensity data is compressed and thus, denaturated.
But the error should be handle by MASH, I will manage that.

Best,
Mélodie
