### ISSUE TITLE
Spotting tool being funny with a 2048x2048 video

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#125]
Hi Melodie,

My image in the spotting tool keeps turning orange whenever I try to spot a molecule. I am assuming this is due to the image being much larger, but it is quite inconvenient as our camera takes videos at 2048x2048. You can see what I mean in the image below:
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/0df3eb54-d12f-4651-bd8a-4ce41d689810)

Also, I have noticed that as the size of the video increases, the size of the molecules in the spotting tool decreases which makes sense. However, it does make it difficult to spot them accurately. Is there any zoom function in the spotting tool that I can use? If not, would it be possible for you to add a zoom function? 

Many Thanks,
Sydney Nguyen

**Comment by mca-sh** [comment]
Hi Sydney and thank you for the report.

Just to let you know, I am on it, it just takes some time.
Indeed, the color scaling  was not done correctly.
I will come back to you when the zoom function is implemented.

Mélodie

**Comment by snguyen49** [comment]
Thank you!

**Comment by mca-sh** [comment]
Hi Sydney,

The color scaling has been corrected and a zoom function is now available in the new version.
You can download the source code here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip

I've tested it on simulated data, it should work.
Don't hesitate to re-open the issue or to open another one if you encounter some bugs.

Best,
Mélodie
