### ISSUE TITLE
Exporting traces to text files without FRET gives an error

### ISSUE THREAD

**Issue by ckjohnson517** [RNA-FRETools/MASH-FRET#133]
**Describe the bug**
Cannot export traces (with no FRET calculation) as text file.  This seems to be the same error described in bug report: Export traces #89. I downloaded the latest version of MASH-FRET, but the error still occurs. 

**To Reproduce**
1. Go to 'Trace Processing'
2. Click on 'EXPORT.'
3. Scroll down to 'Export Time Traces'. Other exports deselected. 

**Error Code**
Copy and Paste the full error code in Matlabs command history.
An error occurred during processing of molecule n:°1:
      Index in position 1 exceeds array bounds.
function: saveProcAscii, line: 320
function: pushbutton_next_Callback, line: 51

**Expected behavior**
Text files downloaded to selected directory. 

**Screenshots**

**Project file(s)**
If applicable, attatch the `.mash` files concerned by the bug.  Github does not accept .mash file attachments. 

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10] Windows 10Pro
 - Matlab Version [e.g. 2016a] 2023a
 - MASH-FRET Version [1.1.2] 1.3.2

**Additional context**

**Your contact**
Leave your email address. ckjohnson@ku.edu

**Comment by mca-sh** [comment]
Hello and thank you for reporting this bug,

Indeed this is the same bug, but the fix is apparently not appropriate to your case.
To fix the problem I will need your .mash file (please, send it to melodiehadzic@protonmail.com) and a few other things:
- a screenshot of the "Export options" window with your own settings
- what was your answer to the question "Automatically process unprocessed molecules?" after pressing `Next`?

Best,
Mélodie

**Comment by mca-sh** [comment]
Hello Carey and thank you for the email,

I had a different bug when opening your project, and after fixing it, it works fine for me.
Could you please have a look if it works also for you with the new version: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip

Best,
Mélodie

**Comment by ckjohnson517** [comment]
Hello Mélodie,

Yes, that works!  Thank you so much for your help.

With best regards,
Carey

**Comment by mca-sh** [comment]
Hello Carey, and thank you for helping developing MASH.
I will close the issue now, do not hesitate to post a new one if you encounter another problem.

Best,
Mélodie
