### ISSUE TITLE
Exporting trajectories and information for only one molecule

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#137]
Hi Melodie,

I am currently trying to export the trajectories of only one or a few molecules and create a separate trajectory project for these molecules. Is that possible? Whenever I attempt to do this, the traces come out looking like the photo below: 
![image](https://github.com/user-attachments/assets/21b1a4bc-943c-4478-bf84-3beadfab9f3f)

This is the original trajectory of the molecule:
![image](https://github.com/user-attachments/assets/4d99734d-a860-4615-99d0-d012ebc5feed)

Did I do anything wrong in exporting the trace file? 
Also, is it possible for me to compile individual trajectories and coordinates molecules from other projects together?

Many Thanks,
Sydney Nguyen

**Comment by snguyen49** [comment]
Hi Melodie,

I think I have found the problem. All of the exported .txt files look like this:
![image](https://github.com/user-attachments/assets/4e912045-ee00-4024-b23c-248e4550d9e1)

**Comment by snguyen49** [comment]
Nevermind. I figured it out. My apologies.

**Comment by mca-sh** [comment]
Hi Sydney,
Sorry for the delayed answer, I was actually giving birth ;)
So if I understood correctly, the mistake came from an incorrect parametrization of the trajectory [file structure](https://rna-fretools.github.io/MASH-FRET/tutorials/set-experiment-settings/import-trajectories.html#file-structure) in the experiment settings?
Best,
Mélodie

**Comment by snguyen49** [comment]
Hi Melodie,

Yes. I am a bit new to a lot of this stuff technologically, so I had to be taught what a delimiter was. Also, I know I'm a random stranger, but congratulations! It's good that you had a safe delivery.

Many Thanks,
Sydney Nguyen
________________________________

**Comment by mca-sh** [comment]
Hi Sydney,

Ok then I will close this issue, do not hesitate to reopen it if you find a bug.

Thank you very much for your kind words :)

Mélodie
