### ISSUE TITLE
Excising photoblinking segments 

### ISSUE THREAD

**Issue by supazel** [RNA-FRETools/MASH-FRET#20]
If during 400 ms photoblinking over 50 ms or longer takes place, it would be great to excise this part and to use only the two flanking regions. So far, only cutting off the trace is possible. This would increase the amount of data

Susann Zelger-Paulus

**Comment by mca-sh** [comment]
I add it to the list and will come back to you when it is set.

**Comment by mca-sh** [comment]
The functionality is implemented in MASH-code-15 and will be available in the next release!
