### ISSUE TITLE
Bug in traces processing tab

### ISSUE THREAD

**Issue by supazel** [RNA-FRETools/MASH-FRET#21]
**Describe the bug**
changing the parameters in the dwell time processing window leads to the deletion of a whole trace, not reversible, reloading the sif file again is the only solution at the moment

**Comment by mca-sh** [comment]
Hi Susi,
- by deleting you mean no trace is displayed right?
- which parameter did you change?
- which version of MASH-FRET (which branch?) are you using?
- could you send me the project file?

**Comment by supazel** [comment]
Hi MASH-Author,
 by deleting you mean no trace is displayed right? -> yes

which parameter did you change? -> changing any type of parameters e.g. vbFRET or StASi

which version of MASH-FRET (which branch?) are you using? -> MASH_26d50a4

could you send me the project file? -> this happens to any projects! I can put it on the exchange folder, because it might be to large to send per mail


who are you?

cheers
.............................................................................

Dr. Susann Zelger-Paulus

University of Zurich, Department of Chemistry,
Winterthurerstrasse 190, CH-8057 Zurich, Switzerland
Tel.: +41 (0)44 63 565 86
susann.paulus@uzh.ch
.............................................................................

-----"mca-sh" <notifications@github.com> schrieb: -----
An: "RNA-FRETools/MASH-FRET" <MASH-FRET@noreply.github.com>
Von: "mca-sh" <notifications@github.com>
Datum: 26.03.2019 14:23
Kopie: "supazel" <susann.paulus@uzh.ch>, "Author" <author@noreply.github.com>
Betreff: Re: [RNA-FRETools/MASH-FRET] Bug in traces processing tab (#21)

Hi Susi,
  by deleting you mean no trace is displayed right?
 which parameter did you change?
 which version of MASH-FRET (which branch?) are you using?
 could you send me the project file?

**Comment by mca-sh** [comment]
It's Mélodie,

It seems like the version you are using dates from the Nov 15, 2018.
You may try with the latest version of the master branch (download [here](https://github.com/RNA-FRETools/MASH-FRET))

**Comment by mca-sh** [comment]
This bug should be fixed in the next release.
