### ISSUE TITLE
Excluding single labeled molecules automatically

### ISSUE THREAD

**Issue by supazel** [RNA-FRETools/MASH-FRET#23]
Excluding single labeled molecules according to the e.g. low fluorescent intensity or stoichiometry of either 1 or 0 within the trace manager would be great and drastically reduce the number of molecules you have to go through manually, which would save a lot of time!!!!

**Comment by mca-sh** [comment]
This is a nice feature, thank you.
I add it to the list and will come back to you when it will be set.

**Comment by mca-sh** [comment]
This feature will be included in the next release, thank you for your contribution !
