### ISSUE TITLE
MASH-FRET bug report

### ISSUE THREAD

**Issue by Kevinkraft7** [RNA-FRETools/MASH-FRET#24]
**Describe the bug**
When you want to transform your input file during the coordinates transformation using MASH-FRET 1.1.2 the process does not start. The window showing you where it will be saved does not show up aswell before the process would start and you get the posted error code in the command window of matlab .

**To Reproduce**
1. Go to video processing in MASH-FRET and perfom all the steps till you want to transform your input coordinates file.
2. Click on transfrom (window for selectino of file does not show up and process does not start)
3. Scroll down in command window right after spots coordinates have been successfully written...

**Error Code**

Error using feval
Undefined function handle.

Error in tform (line 55)
X = feval( t.(f.fwd_fcn), U, t );

Error in tforminv (line 67)
varargout = tform('inv', nargout, varargin{:});

Error in applyTrafo (line 62)
                        tforminv(tr_ij, coord_i{i});

Error in pushbutton_trGo_Callback (line 16)
        coordTrsf = applyTrafo(h.param.movPr.trsf_tr, ...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MASH (line 19)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MASH('pushbutton_trGo_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Expected behavior**
I would expect that the window with the path where it will be saved opens and the transformation starts after selecting it

**Screenshots**
![image](https://user-images.githubusercontent.com/48956713/55019180-b3488680-4ff4-11e9-8fd3-42285e291963.png)

![image](https://user-images.githubusercontent.com/48956713/55019220-c3606600-4ff4-11e9-860a-b555b3b3ffd1.png)

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Matlab Version [ 2018b]
 - MASH-FRET Version [bc9b504]

**Additional context**
We tried it on a laptop with the same transformation file and input coordinates file and there it worked as intended. The laptop is using windows 10 the same MASH-FREt version but matlab2017a instead of 2018b.

**Your contact**
Kevin Kraft
kevin.kraft@uzh.ch

**Comment by mca-sh** [comment]
Hi Kevin,

Thank you for your post.
Could you please send me the transformation file (on Slack it's ok)
This looks like a problem of compatibility with the new Matlab version.

**Comment by mca-sh** [comment]
After a deeper look into this I have some information.
This error can happen when the Image processing toolbox of MATLAB is not installed.
You can checked if it is installed on your computer by typing the command "ver" in MATLAB command window and look for "Image Processing Toolbox".

**Comment by mca-sh** [comment]
We tried to fix this bug in the next release.
The software will be tested with your MATLAB version to be sure the bug is fixed

**Comment by mca-sh** [comment]
Hi Kevinkraft7,
Was the issue fixed for you with the latest release?
Again, I couldn't reproduce it with my setup.
