### ISSUE TITLE
MASH-FRET bug report

### ISSUE THREAD

**Issue by supazel** [RNA-FRETools/MASH-FRET#49]
**Describe the bug**
The "view on video" shows the video view upside down to the original one.

**To Reproduce**
1. Go to 'Trace manager'
2. Click on 'view on video'

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]
 - Matlab Version [e.g. 2017a]
 - MASH-FRET Version [1.1.2]

**Your contact**
Susann Zelger-Paulus
susannpaulus@uzh.ch

**Comment by mca-sh** [comment]
Hi supazel,
Well seen, and thank you for the report.
The image view has been corrected (corrected version: [dowload here](https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-10.zip))

I close the issue.
