### ISSUE TITLE
I have a great idea I need to share with you developer guys

### ISSUE THREAD

**Issue by supazel** [RNA-FRETools/MASH-FRET#65]
**Is your feature request related to a problem? **Yes**.**

It happens very often that I edit the same file in different modules. E.g., I have a look at the TDP or Histogram and simultaneously on the single traces in TP. In the TDP I am working on the clustering and saving the file while I have a look at the single traces if the transitions/states are there too. Then, in TP I am applying different tags, but now they are not updated in the TA, on the other hand, the clustering is not updated in the TP. Basically I am modifying and saving the same file in parallel, in the end, I have two different files. One with the information about the clustering and a second containing the tag information. Do you have an idea how to overcome this? 

**Describe the solution you'd like**
Is it possible to update the file in different modules or even better, the file you open in TP or HA or TA is automatically open in all the other modules as well. 

**Your contact information**
susann.paulus@chem.uzh.ch

**Comment by mca-sh** [comment]
Hi supazel,

Thank you for your feedback and recommendation.
The fusion of project management area of modules TP, TA and HA is one of the first features that will next be implemented. We just need to be patient :)
I will come back to this issue when the implementation is done.

**Comment by mca-sh** [comment]
Hello supazel,

The project management area is now common to all modules.
You can find the pre-release version of MASH here:  [https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/project-list-unification.zip](https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/project-list-unification.zip)

These modifications will be included in the next release (MASH-FRET 1.3.3)

Thank you for your contribution!
