### ISSUE TITLE
MASH-FRET bug report

### ISSUE THREAD

**Issue by Befazl** [RNA-FRETools/MASH-FRET#66]
**Describe the bug**
- Bin time axis:
I have been trying to bin the time axis of exported ASCII files from a MASH file. It is possible to define a new bin time in the first pop-up, and also to select the source folder where the ASCII are stored and to run, MASH does not save any files and the error showed below is coming up.

**To Reproduce**
1. Go to 'Tools'
2. Click on bin time axis and define a new bin time (e.g. 0.1 s)
3. Choose source folder of exported ASCII files

**Error Code**
Error with file n°:279, L14_10mM_autotag_G045_2ndsort_mol9of279.txt
Unrecognized function or variable 'pname_out'.
in function: binTrajFiles, line: 88

**Expected behavior**
A new folder with ASCII files of the binned traces
**Screenshots**

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Matlab Version [2019b]
 - MASH-FRET Version [1.1.2, prev. commit: 86500f0]

**Additional context**

**Your contact**
besim.fazliji@chem.uzh.ch

**Comment by Befazl** [comment]
**Describe the bug**

Bin time axis:
I have tried binning the time axis via using this separate function:
[binTrajFiles.zip](https://github.com/RNA-FRETools/MASH-FRET/files/4769880/binTrajFiles.zip)
Running the function, you can choose the source folder and it also generates a "binned" folder, but it does not generate the binned files and it shows an error.

**To Reproduce**
Steps to reproduce the behavior:

•	Open Matlab
•	Open the function binTrajFiles.m and run (important: add to path)
•	Make sure that only unstructred files are in the folder of your choice (note: the files should not be restructured, all exported ACII files are not restructured, can be easily figured out by opening one file and look if there is one column per excitation wavelength, the files are not restructred)
•	Editor window: copy line no 5 to the command window (the whole path without the %)
binTrajFiles(['C:\Besim\06_data smFRET\L14_17_15_mW\L14_10mM\L14_10mM_merged\L10_10mM_2nd sort_all\traces_ASCII'], 0.10175);
0.1075 is the binning time here
•	Change the path to the path you want
•	binTrajFiles(['D:\0100_Projects\PJ001_smFRET_invivo\016_RawData\0113_smFRET\20170809\all_20170809_25C\20170809_25C_all'], 0.10175);
•	Press enter or Run -> a new folder called binning is created
•	See error

**Error Code**
Error with file n?:1, L14_10mM_autotag_G045_2ndsort_mol100of279.txt
Index exceeds the number of array elements (0).
in function: arrangeColumns, line: 180

**Expected behavior**
A new folder with ASCII files of the binned traces

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
OS [Windows 10]
Matlab Version [2019b]
MASH-FRET Version [1.1.2, prev. commit: 86500f0]

**Additional context**
Add any other context about the problem here.

**Comment by mca-sh** [comment]
Hello Befalz and thank you for reporting these bugs.
I've just made the appropriate corrections in the branch MASH-code-16.
You can download the new version of MASH-FRET here: [https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip](https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip).
Please tell me if it works for you too so I can close/not the issue.

Also I have one comment on the steps to reproduce in your second report: the folder path comes in the second argument of the function, such as:
`binTrajFiles(0.10175, ['D:\0100_Projects\PJ001_smFRET_invivo\016_RawData\0113_smFRET\20170809\all_20170809_25C\20170809_25C_all']);`

**Comment by Befazl** [comment]
Hi mca-sh! 
Thank you very much for the quick response and fix of this issue! It works now perfectly. :)

**Comment by Befazl** [comment]
Hi Mélo,

Thank you again for the fast fix of this issue :) Really appreciate it! 

Could you tell me how the binning is calculated in detail? My initial thought was that, when I am binning the time axis, all counts in the defined bin are summed up and displayed, but apparently it is not. Possibly I just don't get how it is calculated. I was looking also in the documentation, but I didn't find anything.

E.g. in the following trajectory:

The non-binned data has a time res. of 30 ms, and in the traces you see that the intensity of counts is around 3000 counts:


When I bin the data to 90 ms, I expected to have 9000 counts in the y-axis, but it is still 3000:



Best wishes from rainy, rainy Switzerland :) 

Besim


-----"Mélodie Hadzic" <notifications@github.com> schrieb: -----
An: "RNA-FRETools/MASH-FRET" <MASH-FRET@noreply.github.com>
Von: "Mélodie Hadzic" <notifications@github.com>
Datum: 14.06.2020 13:59
Kopie: "Befazl" <besim.fazliji@chem.uzh.ch>, "Author" <author@noreply.github.com>
Betreff: Re: [RNA-FRETools/MASH-FRET] MASH-FRET bug report (#66)


 Hello Befalz and thank you for reporting these bugs.
 I've just made the appropriate corrections in the branch MASH-code-16.
 You can download the new version of MASH-FRET here: https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip.
 Please tell me if it works for you too so I can close/not the issue.
 Also I have one comment on the steps to reproduce in your second report: the folder path comes in the second argument of the function, such as:
 binTrajFiles(0.10175, ['D:\0100_Projects\PJ001_smFRET_invivo\016_RawData\0113_smFRET\20170809\all_20170809_25C\20170809_25C_all']);

**Comment by mca-sh** [comment]
Hi Besim!
Sorry for the so-formal replay on Github: I never know if you will feel
offended if I get too familiar on internet so I prefere to keep it
anonymous ;)
Indeed, the counts are averaged and not summed up, this should be corrected
(though it does not make a difference of FRET and Stoichiometry values).
However, going through the code I realized that the binning is not done
correctly: after binning, the starting points of red and green axis are
still shifted by the old time bin.
I will re-adjust this today and come back to you when it is done!

**Comment by Befazl** [comment]
Hello mca-sh!

Thank you for the explanation and the fix! 
I have received your newest version [1.1.2, prev. commit: 1ed721a] and tried the binning again.

Unfortunately, the binning was not possible. You find the description similar to the initial one below. Thanks again for your help and explanation!

**Describe the bug**

**Bin time axis:**
I have been trying to bin the time axis of exported ASCII files from a MASH file. It is possible to define a new bin time in the first pop-up, and also to select the source folder where the ASCII are stored and to run, MASH does not save any files and the error showed below is coming up.
**To Reproduce**
Steps to reproduce the behavior:

Go to 'Tools'
Click on bin time axis and define a new bin time (e.g. 0.1 s)
Choose source folder of exported ASCII files
See error

**Error Code**
Error with file n°:1, L14_10mM_autotag_G045_2ndsort_mol100of279.txt
Undefined function 'binData2' for input arguments of type 'double'.
in function: binTrajFiles, line: 144

**Expected behavior**
A new folder with ASCII files of the binned traces
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

OS [Windows 10]
Matlab Version [2019b]
MASH-FRET Version [1.1.2, prev. commit: 1ed721a]
**Additional context**
Add any other context about the problem here.

**Comment by Befazl** [comment]
Hello mca-sh!

Thank you for the explanation and the fix!
I have received your newest version [1.1.2, prev. commit: 1ed721a] and tried the binning again.

Unfortunately, the binning was not possible. You find the description similar to the initial one below. Thanks again for your help and explanation!

**Describe the bug**

**Bin time axis:**
I have been trying to bin the time axis of exported ASCII files from a MASH file. It is possible to define a new bin time in the first pop-up, and also to select the source folder where the ASCII are stored and to run, MASH does not save any files and the error showed below is coming up.
**To Reproduce**
Steps to reproduce the behavior:

Go to 'Tools'
Click on bin time axis and define a new bin time (e.g. 0.1 s)
Choose source folder of exported ASCII files
See error

**Error Code**
Error with file n°:1, L14_10mM_autotag_G045_2ndsort_mol100of279.txt
Undefined function 'binData2' for input arguments of type 'double'.
in function: binTrajFiles, line: 144

**Expected behavior**
A new folder with ASCII files of the binned traces
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

OS [Windows 10]
Matlab Version [2019b]
MASH-FRET Version [1.1.2, prev. commit: 1ed721a]
**Additional context**
Add any other context about the problem here.

**Comment by mca-sh** [comment]
Oh my.. I forgot to rename the function within the file.
Ok NOW it should be fine:  [https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip](https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip).

**Comment by Befazl** [comment]
Hello mca-sh!
Now it works perfectly. Thanks again!
