### ISSUE TITLE
MASH-FRET bug report

### ISSUE THREAD

**Issue by Befazl** [RNA-FRETools/MASH-FRET#67]
**Describe the bug**

While video processing, it is not possible to put in the coordinates via coordination file (...ace.coord)
I tried with newly generated coordination files, as well as with coordination files generated with older MASH versions. Both resulted in the same error message.

**To Reproduce**
1. Go to Video processing
2. Click "Load..." to upload a movie file (.sif)
3. Click on "Input coordinates" in the intensity integration panel

**Error Code**
09:21 -- Load coordinates ...
Index in position 1 exceeds array bounds (must not exceed 1).

Error in orgCoordCol (line 44)
            if x_col(i,1)>nCol || y_col(i,1)>nCol

Error in pushbutton_TTgen_loadCoord_Callback (line 43)
coord_itg = orgCoordCol(fDat, 'cw', p.itg_impMolPrm, p.nChan, ...
 
Error while evaluating UIControl Callback.

>> 

**Expected behavior**
Upload of the coordination file

**Screenshots**

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Matlab Version [2019b]
 - MASH-FRET Version [1.1.2, prev. commit 1a1f465]

**Additional context**
I have also applied the routine tests integrated in MASH to check for all functionalities, where further Errors were generated. Please see attached word file.
[20200924_MASH_bug report.docx](https://github.com/RNA-FRETools/MASH-FRET/files/5281214/20200924_MASH_bug.report.docx)

**Your contact**
besim.fazliji@chem.uzh.ch

**Comment by mca-sh** [comment]
Hello Befazl,
I see that you are using the MASH-FRET-17 branch, which is in construction and not usable for now.
Please use the MASH-FRET-16 branch, or download the last version here: [https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip](https://github.com/RNA-FRETools/MASH-FRET/archive/MASH-code-16.zip).
Please tell me if you still get issues with this version.

**Comment by Befazl** [comment]
Dear mca-sh,

Thank you a lot for your answer. I have tested also with the MASH-FRET-16 branch, and I received the exact same error messages. 
I have also downloaded and tested with MASH prev.commit e6bd182 which was uploaded 4 days ago, unfortunately with the same result, except that the routine testing for the Transition analysis was now successful. For all others, I received the exact same error. Unfortunately, I also cannot upload the coordination file in video processing, since also here I get the exact same error as before.

Thanks you a lot for your help.

**Comment by mca-sh** [comment]
Hello Befazl,

Mmm.. I am confused since in my case, importing .coord files causes no errors and the interface testing gives no error and asks nothing from the user in my case.
I am sorry if this is a too trivial remark, but did you remove the MASH-code-17 from the search path of MATLAB (or delete it from your computer) before running MASH-code-16?
Also, may I have your .coord file?
Thanx!

**Comment by mca-sh** [comment]
The issue was solved so I close it.
