### ISSUE TITLE
Error when opening an already video-processed .mash project

### ISSUE THREAD

**Issue by Befazl** [RNA-FRETools/MASH-FRET#80]
**Describe the bug**
Corrupted MASH files. After video processing, some MASH files cannot be reopened and only a error appears.

**To Reproduce**

**Error Code**
Error using bfGetReader (line 85)
Java exception occurred:
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
    at java.util.ArrayList.get(ArrayList.java:433)
    at loci.formats.in.CellSensReader.parseETSFile(CellSensReader.java:1198)
    at loci.formats.in.CellSensReader.initFile(CellSensReader.java:734)
    at loci.formats.FormatReader.setId(FormatReader.java:1421)
    at loci.formats.ImageReader.setId(ImageReader.java:849)
    at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
    at loci.formats.ChannelFiller.setId(ChannelFiller.java:223)
    at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
    at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:293)

Error in readBf (line 29)
    r = bfGetReader(fullFname, 0);
Error in getFrames (line 16)
            [data,ok] = readBf(fullFname, n, param, h_fig, useMov);
Error in checkField (line 152)
        [data,ok] = getFrames([pname fname], 1, {}, h_fig, false);
Error in loadProj (line 38)
        [s,ok] = checkField(s, [pname fname{i}], h_fig);
Error in pushbutton_openProj_Callback (line 86)
    [dat,ok] = loadProj(pname, fname, [], h_fig);
Error while evaluating UIControl Callback.

**Expected behavior**
Open the MASH file after video processing
**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Windows 10
 - Matlab Version 2021B
 - MASH-FRET Version [1.3.2] bf9e2ee8

**Additional context**
**Your contact**
besim.fazliji@chem.uzh.ch
[_20220328_PJ19_01_stoich-sort.zip](https://github.com/RNA-FRETools/MASH-FRET/files/9017015/_20220328_PJ19_01_stoich-sort.zip)

**Comment by mca-sh** [comment]
Hello Befazl,

Thank you for reporting this bug.
I would need the video file that is assigned to the .mash project file, it seems that the error comes from the video reading.
Could you send it to me somehow?

Thank you,
Mélodie

**Comment by mca-sh** [comment]
Hello Befazl, 

Thank you for the video file.
It seems the Bioformat reader needs also the .vsi file.
I get this error message when trying to import your .mash project with your .ets video file:
`loci.formats.FormatException: Could not find .vsi file.`

Is there any chance I can get this one to?

Thank you,
Mélodie

**Comment by mca-sh** [comment]
Hello Befazl,

After several trials, I figured out that the Bioformat readig function is using a particular file naming and folder structure.
the .vsi and .ets files need to be organized as follow:

folder1
---|___ [vsi-file-name].vsi
---|___ **folder2**
-------------- |___ folder3
------------------------|___ [ets-file-name].ets
With **folder2** being name as "**\_[vsi-file-name]\_**" with the two flanking underscores.
Also, there must be only one .vsi and one .ets file in this set to avoid conflicts.

This worked for me, please tell me if it does for you.

Best,
Mélodie

**Comment by Befazl** [comment]
Dear Mélodie

We have tried and it is working. Thank you very much for the solution!

All the best,
