### ISSUE TITLE
MASH projects cannot be merged

### ISSUE THREAD

**Issue by Befazl** [RNA-FRETools/MASH-FRET#87]
**Describe the bug**
MASH fails to merge projects.

**To Reproduce**
1. Select two or more projects
3. Right click
4. Select "merge projects"
5. A warning pops up, that data such as single molecule videos will be lost such as crosstalks parameters will be taken from the first movie. Click yes
6. See error

**Error Code**
Unable to perform assignment because the size of the left side is 15-by-2 and the size of the right side is 15-by-1.

Error in menu_projMenu_merge_Callback>extendTags (line 316)
    molTag_ext(:,~cellfun('isempty',strfind(namesRef,names{tag}))) = ...

Error in menu_projMenu_merge_Callback (line 209)
    s.molTag = cat(1,s.molTag,extendTags(p.proj{proj}.molTag,...
 
Error while evaluating Menu Callback.

**Expected behavior**
Merging of projects.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS [e.g. Windows 111]
 - Matlab Version [e.g. 2022B]
 - MASH-FRET Version [1.3.2] prev. commit 3713f5e8

**Additional context**
n/a

**Comment by mca-sh** [comment]
Hello Besim and thank you for the bug report.
There is definitely a mishandling of the case where a particular tag name is included in another tag name.
I made the necessary modifications in the branch "fix-merge-issue", available for download here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/fix-merge-issue.zip

Can you tell me if it is working for you? In this case, I will merge this modification in the main branch.

Mélodie

**Comment by Befazl** [comment]
Dear Mélodie,

Thank you very much for the fix! Yes, it is working now. 
However, I have a small issue with merging. We can't merge some traces due to different frame rates. I assume the root cause for this is that the frame rate given by the measurements differs in the last digit, stemming from a rounding up or down. How can we tell the software to accept that difference?

**Comment by mca-sh** [comment]
Hi Besim,Thank you for your feedback.
I see the problem and I will think about a solution.
But first I need to close this issue to open a new one ;)
