### ISSUE TITLE
MASH-FRET bug report: Export traces

### ISSUE THREAD

**Issue by nsivan16** [RNA-FRETools/MASH-FRET#89]
**Describe the bug**
- Cannot export traces as txt file

**To Reproduce**
1. Go to 'Trace processing'
2. Click on 'Export'
3. Toggle only  'Export time traces'; intensity time traces
4. can choose directory. But nothing happens.

**Error Code**

Export processed data for selected molecules ...
export data of molecule n:°1(1 on 62)...
16:42 An error occurred during processing of molecule n:°1:
      Index in position 1 exceeds array bounds.
function: saveProcAscii, line: 320
function: pushbutton_next_Callback, line: 51

**Expected behavior**
Data get exported.

**Screenshots**
The bar do not fill. 
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/e02c587f-bd79-4ef7-acd9-f72d888d22ce)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Matlab Version R2022b
 - MASH-FRET Version [1.3.3.1]

**Your contact**
nirusan.sivanantharasa@uzh.ch

**Comment by nsivan16** [comment]
Hi Mélodie,

Please find my mash file in the attachment. I tried to export several files, but all of them had the error I mentioned.

Thanks,
Nirusan
________________________________

**Comment by mca-sh** [comment]
Hi Nirusan,
Thank ou for these precisions.
However, I can't find the attatchement, could you re-sent it to me please?
Thank you!
------- Original Message -------

**Comment by nsivan16** [comment]
Hi Mélodie,

I can see the attachment. But let me try to send it again. If it does not work again, can you send me your e-mail address so that I can send it to you directly.

Thanks,
Nirusan
________________________________

**Comment by mca-sh** [comment]
Hello Nirusan and thank you for the files.
There is indeed a mishandling of the export option when no FRET calculation in defined.
I fixed the bug from my side, I hope it is working for you.
The modified version of MASH is available for download here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/export-trace-wo-fret.zip

Can you please give me a feedback so I either look for further bug fix or merge the corrected version with the main branch?
Thanks.

Mélodie

**Comment by nsivan16** [comment]
Hi Mélodie,

Sorry for the delayed response. I've tried it with multiple non-FRET data and the export works again. But the merging is not available with this version dueto different frame rates. I just checked this.

Thank you
Nirusan
________________________________

**Comment by mca-sh** [comment]
Hi Nirusan and thank you for the feedback.
For merging projects with different frame rates, I direct you to another issue which is still open: https://github.com/RNA-FRETools/MASH-FRET/issues/90
Your feedback on this one in very welcome, so I can merge the modifications with the main branch.
I will now close this issue.
Mélodie
